version: "3.8"

services:
  eureka:
    build: ./blog-eureka-server
    container_name: blog-eureka
    ports:
      - "18761:8761"
    networks:
      - blog-network

  postgres:
    image: postgres:14-alpine
    container_name: blog-postgres
    environment:
      POSTGRES_DB: blog_article_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blog-network

  mongo:
    image: mongo:7.0
    container_name: blog-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: blog_content_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - blog-network

  redis:
    image: redis:7-alpine
    container_name: blog-redis
    ports:
      - "6379:6379"
    networks:
      - blog-network

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: blog-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - blog-network

volumes:
  postgres_data:
  mongo_data:

networks:
  blog-network:
    driver: bridge
